### PR TITLE
debian zlibg name changed to zlib1g

### PR DESCRIPTION
**Pull request by gnafou**

### CODE REVIEW

**Comment by gforcada** [comment]
@gnafou thanks for the pull request! On the issue https://github.com/plone/Installers-UnifiedInstaller/issues/57 you mention that it is only from Debian8 onwards (I guess) so maybe we should also note that before Debian8 the name is zlibg-dev.

**Comment by gnafou** [comment]
it s true for the current distribution and next ones i know of , it's also true for the former one ... Though i do not know  for the ones before

**Comment by gnafou** [comment]
( same thing with ubuntu )

**Comment by svx** [comment]
@gnafou 

Please do not merge if tests are failing and also, please do not merge your own pull requests :)

**Comment by gnafou** [comment]
sorry .... i'm juste learning ...

**Pull request merged**
