### PR TITLE
Add checkdocs to develop.cfg

### PR DESCRIPTION
**Pull request by svx**
This will add https://github.com/collective/collective.checkdocs to develop.cfg, documentation on docs.plone.org for that is on the way too

### CODE REVIEW

**Comment by jensens** [comment]
Whats the state here?

**Comment by jensens** [comment]
@svx *nudge* just a little comment please ;)

**Comment by svx** [comment]
sorry missed that one.. I am working on that in this branch: https://github.com/plone/Installers-UnifiedInstaller/tree/docs_overhaul.

So after we are done with the new docs release [hopefully sometime end of this week] I will turn back to installer stuff.

**Comment by jensens** [comment]
I just want to verify that this one is still valid and will be worked on, thanks for the comment.

**Comment by svx** [comment]
@smcmahon What is your opinion on that, do you think is would make sense to add this, if yes I will work on that during the upcoming sprint at plone symposium Tokyo

**Comment by smcmahon** [comment]
I think it's a super idea.

**Comment by svx** [comment]
Ok I will include that into https://github.com/plone/Installers-UnifiedInstaller/tree/docs_overhaul

**Comment by gforcada** [comment]
@svx what about this: https://github.com/collective/collective.checkdocs/issues/5

**Comment by smcmahon** [comment]
Manually merged. Thanks!

**Pull request closed without merging**
