### PR TITLE
Final py2.7

### PR DESCRIPTION
**Pull request by tobiasherp**
There is no particular reason not to use the "final" Python 2.7 release 2.7.18, right?

I changed the Python 2.7 version for now; I could imagine to change the built Python 3 version from 3.6.9 to the latest 3.8 version as well.

### CODE REVIEW

**Comment by tobiasherp** [comment]
Since it won't make any sense to spare this for another release, I updated the Python 3 version as well.

Now, how is the proceding? Should I merge the pull request myself, or will someone else want to look into it first?

**Comment by jensens** [comment]
LGTM

**Comment by tkimnguyen** [comment]
Please check with me next time, as I've been the one maintaining the unified installer.

**Comment by jensens** [comment]
Well....

**Pull request merged**
