### PR TITLE
Brazilian Portuguese translation 

### PR DESCRIPTION
**Pull request by patrickmonteiro**
Many Brazilian government agencies use Plone for their portals. So in order to help the Brazilian community and encourage the use of plone, I am providing a translation of README and unified installer documentation.

Example of Brazilian portals:
www.brasil.gov.br
www.mds.gov.br
www.cidades.gov.br
www2.planalto.gov.br
www.serpro.gov.br  (A maior empresa de tecnologia do Brasil)
www.interlegis.gov.br

### CODE REVIEW

**Comment by smcmahon** [comment]
Olá Patrick,

Obrigado. This is very welcome, though we will need your contributor's agreement to merge the changes.

If you're interested in something more, it also should be possible to translate the installer's messages. I say "should" because so far we only have English. If there's a problem with the translation mechanism, let me know and we'll fix it.

Can you also check on the .js file you added? Is that deliberate or accidental?

Steve

**Comment by patrickmonteiro** [comment]
@smcmahon Okay, I can parse console messages too. And do more detailed work on translation.

The file js was by mistake.
To sign the contract should I download it, print it and send it to the scanned email?

**Comment by polyester** [comment]
@patrickmonteiro about the Contributor Agreement: yes, download from [here](https://plone.org/foundation/contributors-agreement), print, fill in your information, scan and send to agreements@plone.org. (If you don't have a scanner handy, a good photo on a mobile phone is also OK)

**Comment by patrickmonteiro** [comment]
@polyester Ok, I just sent!

**Comment by smcmahon** [comment]
Paul confirms he's got your contributor's agreement.

Can you remove the .js file and re-create the pull request without it? 

I'm closing this one. Just open a new one with the change.

Thanks!

**Comment by smcmahon** [comment]
And, if the bot complains about the CA, don't worry. I'll override that.

**Comment by patrickmonteiro** [comment]
@smcmahon  Right!
Right!
Do you think it is necessary to open an issue to discuss the file and folder structure for the translation to be more organized, or keep it the current way and later improve?

**Comment by smcmahon** [comment]
Either is fine. I'll certainly be happy to do (or help with) any reorganization that could help translators.

**Comment by patrickmonteiro** [comment]
Ok, I will refactor a little before sending.

**Pull request closed without merging**
