### PR TITLE
Typo fixed

### PR DESCRIPTION
**Pull request by dbitouze**

### CODE REVIEW

**Comment by jensens** [comment]
@esteele whats the rule here? I think this typo fix can be merged w/0 having a signed contributor agreement, right?

**Comment by dbitouze** [comment]
> I think this typo fix can be merged w/0 having a signed contributor agreement, right?

I fully agree! :)

**Comment by esteele** [comment]
@jensens Correct. We're clear to waive the requirement for typo fixes.

**Comment by tkimnguyen** [comment]
Thank you @dbitouze. You beat me to fixing this typo, but I made the change already 3 months ago. But now we know you can contribute these fixes w/o the contributor agreement (which you should sign anyway!)

**Pull request closed without merging**
